### PR TITLE
Logo idea

### PR DESCRIPTION
**Pull request by kylejohnston**
Added an additional logo concept

### CODE REVIEW

**Comment by pintman** [comment]
It looks rather interesting. I like the reduced and clean approach.

**Comment by pintman** [comment]
Maybe one can combine it with the classical on/off symbol. Like the one here: https://www.freepik.com/free-icon/simple-on-off-button_695266.htm

**Comment by kylejohnston** [comment]
Good idea – added a stylized on/off symbol and refined the numerals. 

If you like, I can export the PNGs at any size (or provide any other image format)

**Comment by pintman** [comment]
Thank you. :) The "on/off-Version" looks really cool. As long as I can reproduce png-versions from the svg-files there is no need for differently sized exports for us.

**Comment by elektroschule** [comment]
@kylejohnston Superb! The logo looks really great. Thanks for the support.

**Pull request merged**
